mkdir -p build
cd build
cmake \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_BUILD_TYPE=Debug \
  -DENABLE_CLANG_TIDY=ON \
  -DENABLE_HEADER_GUARDS_CHECK=ON \
  -DENABLE_CLANG_FORMAT_CHECK=ON \
  -DKSEQPP_READ_BUILD_TESTS=ON \
  -DKSEQPP_READ_BUILD_TESTS=ON \
  ..
cmake --build . -j8
cd ..

